import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontBerk = localFont({
  src: "../../public/berkeley-mono.woff2",
  variable: "--font-berk",
});

const fontInstru = localFont({
  src: "../../public/InstrumentSerif-Regular.woff2",
  variable: "--font-instru",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontBerk.variable} ${fontInstru.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
